services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=user_service
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local